import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

const faqs = [
  {
    question: "Does iLearn download videos from YouTube?",
    answer: "No, iLearn does not download any videos. We use the official YouTube IFrame Player API to embed and control videos directly on our platform, ensuring full compliance with YouTube's terms of service.",
  },
  {
    question: "Who owns the questions generated by the AI?",
    answer: "You do. Any questions generated for your content are yours to use, review, and edit within the iLearn platform. We simply provide the tool to create them.",
  },
  {
    question: "How does iLearn handle student data and privacy?",
    answer: "We take student privacy very seriously. All data is handled securely within your own organizational tenant. We are committed to being compliant with student privacy regulations and store only the minimal data required for the platform to function.",
  },
  {
    question: "What happens if a video doesn't have captions?",
    answer: "If official captions are not available, iLearn provides alternatives. You can upload your own caption file (SRT/VTT). Alternatively, if the video has chapters, iLearn can use chapter titles to create learning checkpoints, though the questions may be less precise.",
  },
  {
    question: "Is iLearn suitable for younger students?",
    answer: "Yes, iLearn is designed with Grades 1-8 in mind. The interface is simple and intuitive, and all AI-generated content is created with strict child-safety guardrails to ensure it's appropriate for the classroom.",
  },
];

const FAQ = () => {
  return (
    <section id="faq" className="py-16 md:py-24 bg-background">
      <div className="container mx-auto px-4 md:px-6">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl md:text-4xl font-headline font-bold text-primary">
            Frequently Asked Questions
          </h2>
          <p className="mt-4 text-lg text-muted-foreground">
            Have questions? We have answers.
          </p>
        </div>
        <div className="mt-12 max-w-3xl mx-auto">
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`}>
                <AccordionTrigger className="text-left font-semibold hover:no-underline">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
};

export default FAQ;
